# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default
  

steps:

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/infrastructure/azure'
    Contents: |
      aks/**
      !.git/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)/akscluster'

- task: TerraformInstaller@1
  displayName: 'Terraform Installation'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV4@4
  displayName: 'Terraform Initialization'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)/infrastructure/azure/aks'
    backendServiceArm: 'TfConnection'
    backendAzureRmResourceGroupName: 'tfstate'
    backendAzureRmStorageAccountName: 'tfstateravi2408'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV4@4
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/azure/aks'
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/azure/aks'
    commandOptions: '-out=tfplan.binary'
    environmentServiceNameAzureRM: 'TfConnection'

- script: terraform show -json tfplan.binary > main.tfplan.json
  displayName: 'terraform show'
  workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/azure/aks'

- task: tfsec@1
  inputs:
    version: 'v1.26.0'
    dir: '$(System.DefaultWorkingDirectory)/infrastructure/azure/aks'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true
    architecture: 'x64'
- script: |
    pip install --upgrade pip
    pip install pytest terraform-compliance
    terraform-compliance -p main.tfplan.json -f features/compliance --junit-xml results.xml
  displayName: 'Install terraform-compliance with pip'
  workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure/azure/aks
  continueOnError: true

- script: |
    pip install checkov
    checkov -d . --skip-path venv --output junitxml > checkov_results.xml
  displayName: 'Checkov scan and results'
  workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure/azure/aks

- script: |
    @powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
    Remove-Item -Path 'C:\ProgramData\chocolatey\lib-bad' -Recurse -Force
    choco feature enable -n=useEnhancedExitCodes
    choco install chocolatey --force
    choco install terrascan -Yes
  displayName: 'Install Chocolatey'
  workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure/azure/aks

- script: |    
    terrascan scan -d . -o xml >  terrascanresults.xml
  displayName: 'Install and run terrascan'
  workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure/azure/aks

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)/infrastructure/azure/aks/*.xml'
    testResultsFormat: 'JUnit'
    testRunTitle: 'JUnit Test Results'
  displayName: 'Publish JUnit Test Results'
- task: PublishBuildArtifacts@1
  displayName: 'Publishing the Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/akscluster'
    ArtifactName: 'drop'
    publishLocation: 'Container'
